### ISSUE TITLE
Missing information on CNE

### ISSUE THREAD

**Issue by synnack** [dvisser/MHI-ESP-PCB#1]
Hi,

Cool project! 
I'm considering assembling something like this PCB or https://github.com/absalom-muc/MHI-AC-Ctrl/blob/master/Hardware.md.

The difference is the presence of something that taps into the infrared port via the CNE connector. 

But what I'm missing is:
1. What does the infrared port allow that the SPI does not have?
2. How is it wired? Is it a tap or Man-in-the-Middle ?

Looking forward to your feedback (also in the .md? :)

**Comment by dvisser** [comment]
Hi,

Answers for you:

1. Our device is a man-in-the-middle so to speak, the firmware repeats any infrared signals from a remote to the unit. The main reason we added this was that "3d auto" isnt available over SPI (there may be some other functions also but this was the main one). 

2. You can either cut a wire, and solder each end to specific pads on our board or unplug the cable from the IR board in the head unit and plug it into our module and then make up a cable from our module and plug it into the control board where the IR board was originally plugged in. 

Hope that makes sense?

Thanks,
Dan

**Comment by synnack** [comment]
Yes, that makes perfect sense. I've also noticed that not all fan modes are available over SPI, but I figured that was just some missing reverse-engineering. Like vanes left/right and I think one of the fan speeds might be missing. Kind of weird that SPI would not have that, though.

**Comment by dvisser** [comment]
Yeah the vanes you mention arent available over SPI either from memory. Hence the need to inject data onto the IR line.

**Comment by dvisser** [comment]
Think we have added the missing fan speed over SPI though.

**Comment by dvisser** [comment]
@TheZeroBeast the above that I have said RE firmware is correct isn't it?

**Comment by dvisser** [comment]
and yes @synnack, I need to update the readme.md :-) thanks for the reminder!

**Comment by TheZeroBeast** [comment]
Hey @synnack,

Yeah @dvisser, that’s right, I have auto fan going over IR as it’s not implemented on SPI.

**Comment by dvisser** [comment]
ah right, well there ya go. 

@synnack OK for me to close this issue now?

**Comment by synnack** [comment]
@dvisser If you don't need the reminder to update the .md files, you can close it. I got what I need ;-)

**Comment by dvisser** [comment]
readme.md updated
